plugins {
    id("groovy")
    id("io.micronaut.application") version "5.0.2"
}

version = "0.1"
group = "com.moltenbits"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("info.picocli:picocli-codegen")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("info.picocli:picocli")
    implementation("io.micronaut.picocli:micronaut-picocli")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    runtimeOnly("ch.qos.logback:logback-classic")
}

application {
    mainClass = "com.moltenbits.sideband.SidebandCommand"
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

graalvmNative {
    binaries {
        all {
            buildArgs.add("-H:+SharedArenaSupport")
            resources.includedPatterns.add("skills/.*")
        }
    }
}

// Bake the build version into a generated source so the native image needs no resource lookup.
val generateBuildVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/sources/buildVersion/java")
    val buildVersion = project.version.toString()
    inputs.property("version", buildVersion)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/moltenbits/sideband/BuildVersion.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.moltenbits.sideband;

            /** Generated by Gradle; do not edit. */
            final class BuildVersion {
                static final String VERSION = "$buildVersion";

                private BuildVersion() {
                }
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets.main {
    java.srcDir(generateBuildVersion)
}

// The executable carries both client skills so `sideband init` can install them anywhere.
val skillManifest by tasks.registering {
    val skillsDir = layout.projectDirectory.dir("skills")
    val outputDir = layout.buildDirectory.dir("generated/resources/skills")
    inputs.dir(skillsDir)
    outputs.dir(outputDir)
    doLast {
        val root = skillsDir.asFile
        val files = root.walkTopDown().filter { it.isFile }.map { it.relativeTo(root).path.replace('\\', '/') }.sorted().toList()
        val manifest = outputDir.get().file("skills/manifest.txt").asFile
        manifest.parentFile.mkdirs()
        manifest.writeText(files.joinToString("\n") + "\n")
    }
}

sourceSets.main {
    resources.srcDir(skillManifest)
}

tasks.processResources {
    from(layout.projectDirectory.dir("skills")) { into("skills") }
}

micronaut {
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("com.moltenbits.sideband.*")
    }
}

// https://docs.gradle.org/current/userguide/upgrading_major_version_9.html#test_task_fails_when_no_tests_are_discovered
tasks.withType<AbstractTestTask>().configureEach {
    failOnNoDiscoveredTests = false
}
