plugins {
    id("groovy")
    id("io.micronaut.application") version "5.0.2"
}

version = "0.1"
group = "com.moltenbits"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("info.picocli:picocli-codegen")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("info.picocli:picocli")
    implementation("io.micronaut.picocli:micronaut-picocli")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    runtimeOnly("ch.qos.logback:logback-classic")
}

application {
    mainClass = "com.moltenbits.sideband.SidebandCommand"
}

java {
    sourceCompatibility = JavaVersion.toVersion("25")
    targetCompatibility = JavaVersion.toVersion("25")
}

graalvmNative {
    binaries {
        all {
            buildArgs.add("-H:+SharedArenaSupport")
        }
    }
}

// Bake the build version into a generated source so the native image needs no resource lookup.
val generateBuildVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/sources/buildVersion/java")
    val buildVersion = project.version.toString()
    inputs.property("version", buildVersion)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/moltenbits/sideband/BuildVersion.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.moltenbits.sideband;

            /** Generated by Gradle; do not edit. */
            final class BuildVersion {
                static final String VERSION = "$buildVersion";

                private BuildVersion() {
                }
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets.main {
    java.srcDir(generateBuildVersion)
}

micronaut {
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("com.moltenbits.sideband.*")
    }
}

// https://docs.gradle.org/current/userguide/upgrading_major_version_9.html#test_task_fails_when_no_tests_are_discovered
tasks.withType<AbstractTestTask>().configureEach {
    failOnNoDiscoveredTests = false
}
